site_name: SutR Dashboard Manual
nav:
  - Login: index.md
  - Ordering Service: ordering-service.md
  - Certificate Authorities: certificate-authorities.md
  - Organizations (MSP): organizations(msp).md
  - Peers: peers.md
  - Channels: channels.md

theme: readthedocs